prioritaires:
  - parcours d'aide

  - mpa . situation demandeur
  - mpa . occupant . condition age ou handicap
  - MPLD . situation demandeur
  - MPLD . bailleur . ampleur travaux
  - copropriété . condition 15 ans
  - copropriété . condition résidence principale
  - MPLD . copropriété . condition arrêté police

  - vous . propriétaire . statut
  - logement . propriétaire occupant
  - logement . résidence principale propriétaire
  - logement . résidence principale locataire
  - logement . adresse
  - logement . type
  - logement . surface
  - logement . période de construction
  - ménage . personnes
  - ménage . revenu
  - logement . commune
  - ménage . commune
  - ménage . personnes
  - ménage . revenu
  - DPE . actuel
  - projet . définition
  - projet . définition . catégories travaux envisagées
  - projet . définition . travaux envisagés
