préface:
  - logement . adresse
  - logement . zone d'exposition
  #prioritaires:
  #  - logement . adresse
chapitres:
  - logement
  - rga
  - - ménage
    - vous
situation:
  logement . propriétaire occupant: oui
  vous . propriétaire . condition: oui
